PassportTracker/Controllers/LocationController.cs
using PassportTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PassportTracker.Controllers
{
    public class LocationController : Controller
    {
          PassportTrackerDB _db;

        public LocationController()
        {
            _db = new PassportTrackerDB();
          
        }

        public LocationController(PassportTrackerDB db)
        {
            _db = db;
        }

        //
        // GET: /Location/
        [SharePointContextFilter]
        public ActionResult Index()
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = _db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InAuthorRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("author")).Count() > 0 ? "true" : "false";
            ViewData["InCountryRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("country")).Count() > 0 ? "true" : "false";

            if ((ViewData["InAuthorsRole"] != "true") && ViewData["InCountryRole"] != "true" && ViewData["InOwnerRole"] != "true")
            {
                return RedirectToAction("Unauthorised", "PassportForm", new { SPHostUrl = SharePointContextFilterAttribute.sphosturl }); //SharePointContext.GetSPHostUrl(HttpContext.Request).AbsoluteUri });
            }

            LocationVM location = new LocationVM();
            location.lawCourtsVM = _db.tblLawCourts
                .Where(a => a.LC_Deleted == false)
                .Select(r => new LawCourtsVM { 
                    VM_LC_Id = r.LC_Id, 
                    VM_LC_Name = r.LC_Name
                }).ToList<LawCourtsVM>();

            location.passportOfficeVM = _db.tblPassportOffice
                .Where(a => a.PO_Deleted == false)
                .Select(v => new PassportOfficeVM
                {
                    VM_PO_Id = v.PO_Id,
                    VM_PO_Location_Country = v.PO_Location_Country,
                    VM_PO_Location_Name = v.PO_Location_Name
                }).ToList<PassportOfficeVM>();


            return View(location);
        }

 

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
	}
}

PassportTracker/Views/Shared/Alert.cshtml
@{
    ViewBag.Title = "Passport Tracket Alert";
}

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()


    <h2></h2>



        @Html.Raw(TempData["alertMessage"])

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



PassportTracker/Views/Shared/Unauthorised.cshtml
@{
    ViewBag.Title = "NJC Events - Unauthorised";
}

@*@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()*@

<h2></h2>    
<h2></h2>
<h4>You are not authorised to view this application. Please contact the administrator.</h4>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@



PassportTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" charset="utf-8" />
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Passport Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-2.0.3.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/DayPilot/daypilot-all.min.js")"></script>

    <link href='@SharePointContextFilterAttribute.sphosturl/_layouts/15/defaultcss.ashx' type='text/css' rel='stylesheet' />
    <script src='@SharePointContextFilterAttribute.sphosturl/_layouts/15/SP.UI.Controls.js'></script>

</head>
<body style="overflow: auto;">
    <div id="chrome_ctrl_container"></div>
    <div class="navbar">
        <div class="container">
            <ul class="nav navbar-nav navbar-right pull-right">
                <li class="navbar-text">Hello, @User.Identity.Name!</li>
            </ul>
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home", new { SPHostUrl = SharePointContextFilterAttribute.sphosturl }, null)</li>
                @if (ViewData["InOwnerRole"] == "true")
                {
                    <li>@Html.ActionLink("Access Control", "Index", "Access", new { SPHostUrl = SharePointContextFilterAttribute.sphosturl }, null)</li>
                      <li>@Html.ActionLink("Locations", "Index", "Location", new { SPHostUrl = SharePointContextFilterAttribute.sphosturl }, null)</li>
                }
                <li>@Html.ActionLink("About", "About", "Home", new { SPHostUrl = SharePointContextFilterAttribute.sphosturl }, null)</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home", new { SPHostUrl = SharePointContextFilterAttribute.sphosturl }, null)</li>

            </ul>
        </div>
    </div>

    <div class="container body-content">
        <input type="hidden" id="SPHostUrl" value=@SharePointContextFilterAttribute.sphosturl />
        @RenderBody()
        <hr />
        @RenderSection("DocumentLog", required: false) <br /> <br />
        <footer>
            <p>&copy; @DateTime.Now.Year Passport Tracker</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/custom")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>